### ISSUE TITLE
Need GC rules for requestKey

### ISSUE THREAD

**Issue by jiyoung-an** [ainize-team/ainize-js#117]
We need to set garbage collection(GC) rules for the `$requestKey` under the service.
Setting these rules would help manage the increase in requests and responses without raising the stacking amount. And to eliminate potential error risks.

**Comment by platfowner** [comment]
test branch: https://github.com/ainize-team/ainize-js/tree/bugfix/jiyoung/gc-rule-test

yarn run test:
![yarn_run_test](https://github.com/ainize-team/ainize-js/assets/46211617/c9968fb4-c824-4d3a-8e31-d8a4df369493)

GET_RULE:
![get_rule2](https://github.com/ainize-team/ainize-js/assets/46211617/f8dc3e1a-cf73-47af-b702-4864122d9d76)

jsonformatter:
![jsonformatter](https://github.com/ainize-team/ainize-js/assets/46211617/e3164d84-418e-4ae6-a88c-5686dd92e9cf)

**Comment by platfowner** [comment]
Resolved, thanks!
